### ISSUE TITLE
Check correct FPGA personality is loaded at start of init

### ISSUE THREAD

**Issue by jacklovell** [petermilne/BOLODSP#14]
We recently had an issue at JET whereby the BOLODSP init script was trying to write register values to the FPGA, but due to an incorrect cfg file there was no FPGA personality loaded. This meant the register write stalled the AXI bus and rendered the system unable to boot. The fix required removing the SD card and moving the bolodsp package out of /mnt/packages.

The package should be more robust to this sort of misconfiguration. Perhaps we should check that the correct FPGA personality is loaded before attempting any register writes. Or perhaps the underlying driver should be modified to prevent deadlock, though that's out of the scope of this package.

**Comment by petermilne** [comment]
Hello Jack

On 30/10/2019 15:00, Jack Lovell wrote:
> We recently had an issue at JET whereby the BOLODSP init script was trying to write register values to the FPGA, but due to an incorrect cfg file there was no FPGA personality loaded. This meant the register write stalled the AXI bus and rendered the system unable to boot. The fix required removing the SD card and moving the bolodsp package out of /mnt/packages.
> 
> The package should be more robust to this sort of misconfiguration. Perhaps we should check that the correct FPGA personality is loaded before attempting any register writes. Or perhaps the underlying driver should be modified to prevent deadlock, though that's out of the scope of this package.
> 

Responding by email since I don't like typing in a box. Ideally, this will end up on github as well..

Thank you very much for your fault report / product complaint.
We appreciate the feedback, and we fully understand wasted time involved when it comes to swapping SD cards.

First, swapping SD should always be a LAST RESORT, since you have the serial console, you can always go to
http://www.d-tacq.com/resources/d-tacq-4G-acq4xx-UserGuide-r29.pdf  #5.8 Emergency Rescue

**** transcript *****
Break to u-boot
setenv EBREAK yes
saveenv
boot
...
bin/sh: can't access tty; job control turned off
/ #  EBREAK / #
/ #  EBREAK / # mv /mnt/local/fmc-scan.conf /mnt/local/__fmc-scan.conf
/ #  EBREAK / # sync;sync;

press reset
acq2006-uboot> setenv EBREAK
saveenv
boot
**** transcript *****

Tedious? Yes. Needs screwdriver? No. Can be done remotely? Yes.

Second, we've been trying to reproduce your exact reported fault, and we can't.

Are you absolutely sure it was an attempted access to AXI that was stalling and causing brickage?.
For that to happen, one of two possibilities:

a/ BOLODSP is accessing the DSP area via a direct mapping on /dev/mem.
We can't stop that, and it's highly unrecommended. Doesn't happen in the version here.

b/ BOLODSP accesses the DSP area via the regfs driver.
Sure enough, bolodsp.init tries to force load this drive regardless of FPGA state.
That's an error, but actually, in our case at least, regfs fails with symbol resolution errors because the acq420fmc driver failed to load.

What does happen for us is: the boot fails, and there's no clean login prompt on the console (in modern software, because it's waiting for IOC_READY, which isn't going to happen, and it would really defeat the object of the wait to make and exception..). So, sure, from the serial console point of view, it's a brick, but it's still possible to log in from ssh, fix things and force a reboot. So we'd say, that's an acceptable way out (considering this is what should be a rare jam).


It does seem to me, that we've only escaped an AXI wedge by luck (missing symbols) rather than design, so I've hardened
10-acq420 and 35-bolodsp with explicit "exit if fpga not loaded". So there definately won't be a bus wedge, but there still won't be a boot prompt at the end in case of error.

Please see latest full release:
https://github.com/D-TACQ/ACQ400RELEASE/releases/tag/v130

Cheers


Peter


-- 
Peter Milne
Director of Sales
www.d-tacq.com

**Comment by jacklovell** [comment]
Thanks Peter. My suspicion that the AXI bus was stalled was based on the following observations:
- The serial terminal was unresponsive to input (typing characters did not show up on the prompt, including ^C)
- The heartbeat LED had stopped flashing
- The hang occurred during 35-bolodsp init; the system never made it as far as loading EPICS and waiting for IOC_READY.

This happened with a pretty old firmware release: the failed upgrade was back in April 2019. So it's possible that newer ACQ400 releases exhibit a different failure behaviour when the FPGA is not loaded.

Booting to the stage of being able to log in via ssh is fine: I'm happy to consider this issue fixed.
