### ISSUE TITLE
Remove old calibration data when COPY_CALIB_DATA is true

### ISSUE THREAD

**Issue by jacklovell** [petermilne/BOLODSP#18]
If a user runs `run_calibfit` after putting `COPY_CALIB_DATA=1` in `/mnt/local/sysconfig/bolo.sh`, data is copied to `tmp/calib_data`. If the user then modifies `BOLO_ACTIVE_CHAN` and re-runs `run_calibfit`, new calibration data overwrites the previous data, but only for the active channels. If channels were active in the first `run_calibfit` run but not in the second, they will retain data from the first calibration. This means there is data from two calibrations mixed together.

If a user sets `COPY_CALIB_DATA=1`, they should expect that the data in `/tmp/calib_data` corresponds only to the most recent calibration. We should therefore remove old results before copying the latest calibration data here.

**Comment by petermilne** [comment]
Disagree. This is how we calibrate all the channels with our limited set of foils.
ie: it's quite possible that calibrations are conducted in series.
Maybe not valid in a real system because the calibrated channels cannot all run with foil they were calibrated with, but we do like to see "all channels calibrated".  If it's an issue for users, they're free to delete /tmp/calib_data.

If you have a full set of foils, then BOLO_ACTIVE_CHAN stays at the max and this doesn't apply.
